# Generated by Django 3.0.5 on 2021-02-07 20:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(default='', max_length=200)),
                ('from_number', models.CharField(default='', max_length=20)),
                ('to_number', models.CharField(default='', max_length=20)),
                ('credit', models.CharField(blank=True, default='', max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('language_code', models.CharField(default='MNk6', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('to_notify', models.BooleanField(default=False)),
                ('indigenous', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('credit_proofed', models.BooleanField(default=False)),
                ('compensation', models.BooleanField(default=False)),
                ('hash_id', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=999)),
                ('zipcodes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('indigenous_cities', models.ManyToManyField(default=None, to='hello.City')),
            ],
        ),
        migrations.CreateModel(
            name='MergedAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_id', models.IntegerField()),
                ('url', models.URLField()),
                ('city_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('compensation', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('credit_proofed', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('phone_number_hash', models.CharField(blank=True, default='', max_length=200)),
                ('hash_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.City')),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.CharField(max_length=40)),
                ('numeric', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Call')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Language')),
                ('participant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_sid', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Call')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('proofed', models.BooleanField()),
                ('url', models.URLField()),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Recording')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.City'),
        ),
        migrations.AddField(
            model_name='call',
            name='participant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Participant'),
        ),
    ]
